version: '3.8'

services:
  app:
    image: meduzzen-internship-front-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    restart: always
    command: npm run start
    environment:
      - NODE_ENV=development
